### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by DDoSolitary** [DDoSolitary/LxRunOffline#9]
- [x] Add Wiki pages for Arch Linux, Fedora, openSUSE, Alpine Linux, etc. (Wiki is publicly editable, any help is appreciated)
- [x] [Fix `LxRunOffline config-env`.](https://github.com/DDoSolitary/LxRunOffline/blob/master/LxRunOffline/Program.cs#L73) (8d53e664fdaa9bb6ac01382190e092b18f97609a)
- [x] Improve console output. Error ouput done (4cb64a5420f470b02b9e5ae30b19f3bc14da5bfc), logging done (d006dc611b27e3320011ad8291b842031eff34ea, 30772efe22dbab3ff753223f72525ac751cbe158).

**Comment by Biswa96** [comment]
May you provide some guidelines for writing the wiki page and its tittle? or How can I write the wiki about that? I have thought a tittle like "Install any Docker tarballs in WSL". How is that?

**Comment by DDoSolitary** [comment]
No special rules, just make sure readers can get what they want. :)

**Comment by Biswa96** [comment]
For the second fix, may be you should add [`WslConfigureDistribution`](https://msdn.microsoft.com/en-us/library/windows/desktop/mt826865(v=vs.85).aspx) function in `WslWinApi.cs` file.

**Comment by DDoSolitary** [comment]
> For the second fix, may be you should add WslConfigureDistribution function in WslWinApi.cs file.

The current approach should work, the only problem is the command line parser doesn't support optional options with array values.

> OpenSUSE is available in Windows store now. Should I write wiki about it?

You don't need to ask me if you want to create a wiki page. And in fact I'm not able to respond quickly in the next few months.

**Comment by Biswa96** [comment]
You've write the registry values manually in WSL.cs but those will be automatically add if you apply the `WslConfigureDistribution` function using default user ID.

**Comment by DDoSolitary** [comment]
But I'm trying to avoid using Win32 APIs to keep flexible for future changes. If I simply use the Wsl* functions, I won't be able add complicated features that the API doesn't support.

**Comment by Biswa96** [comment]
So if you want to fully independent of WSL APIs then you can register distro without that API. Simple `reg add` command and `tar` command add that distro.

**Comment by DDoSolitary** [comment]
- But how to use `tar` under cmd?

- cmd can deal with most registry manipulation but it is really painful to write bat script.

**Comment by DDoSolitary** [comment]
WSL uses NTFS extended attributes to store onwership and permission, see #19
